version: '3'

services:
  synapse:
    image: matrixdotorg/synapse:latest
    restart: always
    ports:
      - "8008:8008"
    volumes:
      - ./synapse_data/:/data/
    links:
      - db
  db:
    image: postgres:alpine
    expose:
      - 5432
    restart: always
    volumes:
     - ./postgres_data/:/var/lib/postgresql/data/
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: matrix
      POSTGRES_PASSWORD: your-secret-pw
